//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CAP_BAC_NHOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_CAP_BAC_NHOM()
        {
            this.DM_CAP_BAC = new HashSet<DM_CAP_BAC>();
        }
    
        public int ID { get; set; }
        public string TEN_NHOM_CB { get; set; }
        public string MO_TA { get; set; }
        public string IS_TAN_BINH { get; set; }
        public Nullable<int> NHOM_CB_CHA_ID { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<int> NGUOI_CAP_NHAT { get; set; }
        public Nullable<int> SO_THU_TU { get; set; }
        public string KY_HIEU_VIET_TAT { get; set; }
        public string MaNhomCB { get; set; }
        public string NhomCBCha_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_CAP_BAC> DM_CAP_BAC { get; set; }
    }
}
