//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHOM_TC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_NHOM_TC()
        {
            this.DM_NHOM_TC_KHU_VUC = new HashSet<DM_NHOM_TC_KHU_VUC>();
            this.TC_CBCS = new HashSet<TC_CBCS>();
            this.TC_DON_VI_NH = new HashSet<TC_DON_VI_NH>();
        }
    
        public int ID_NHOM { get; set; }
        public string TEN_NHOM_TC { get; set; }
        public string MO_TA { get; set; }
        public Nullable<int> LOAI_TC { get; set; }
        public Nullable<int> NIEN_HAN { get; set; }
        public string MUA { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<int> NGUOI_CAP_NHAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_NHOM_TC_KHU_VUC> DM_NHOM_TC_KHU_VUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TC_CBCS> TC_CBCS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TC_DON_VI_NH> TC_DON_VI_NH { get; set; }
    }
}
