//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHOM_SAN_PHAM_BG_D
    {
        public int ID { get; set; }
        public Nullable<int> NHOM_SAN_PHAM_BG_ID { get; set; }
        public Nullable<long> SP_ID { get; set; }
        public string TEN_SP { get; set; }
        public Nullable<int> DVT_ID { get; set; }
        public string TEN_DVT { get; set; }
    }
}
