//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LT_FLEX_VALUE_SETS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LT_FLEX_VALUE_SETS()
        {
            this.LT_FLEX_VALUE_CATEGORIES = new HashSet<LT_FLEX_VALUE_CATEGORIES>();
        }
    
        public int FLEX_VALUE_SET_ID { get; set; }
        public string FLEX_VALUE_SET_NAME { get; set; }
        public string LAST_UPDATE_DATE { get; set; }
        public Nullable<int> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public string DESCRIPTION { get; set; }
        public string ENABLED_FLAG { get; set; }
        public string FLEX_TYPE { get; set; }
        public string SCOPE { get; set; }
        public string FORM_DISPLAY_FLAG { get; set; }
        public string APP_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LT_FLEX_VALUE_CATEGORIES> LT_FLEX_VALUE_CATEGORIES { get; set; }
    }
}
