//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LT_FLEX_VALUE_CATEGORIES
    {
        public int FLEX_VALUE_CATEGORY_ID { get; set; }
        public int FLEX_VALUE_SET_ID { get; set; }
        public string FLEX_VALUE_CATEGORY { get; set; }
        public string DESCRIPTION { get; set; }
        public string BRIEF_NAME { get; set; }
        public string ENABLED_FLAG { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<int> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<int> PARENT_FLEX_VALUE_CATEGORY { get; set; }
        public string NOTE { get; set; }
        public string DATA_SOURCE { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
    
        public virtual LT_FLEX_VALUE_SETS LT_FLEX_VALUE_SETS { get; set; }
    }
}
