//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QS_CBCS_SD
    {
        public long ID_ { get; set; }
        public int DON_VI_ID { get; set; }
        public int NAM { get; set; }
        public string KY { get; set; }
        public Nullable<int> CAP_BAC_ID { get; set; }
        public Nullable<int> LOAI_HAM_ID { get; set; }
        public int LUC_LUONG_ID { get; set; }
        public Nullable<int> SL_NAM_DK { get; set; }
        public Nullable<int> SL_NU_DK { get; set; }
        public Nullable<int> SL_NAM_TK { get; set; }
        public Nullable<int> SL_NU_TK { get; set; }
        public Nullable<int> SL_NAM_DEN { get; set; }
        public Nullable<int> SL_NU_DEN { get; set; }
        public Nullable<int> SL_NAM_DI { get; set; }
        public Nullable<int> SL_NU_DI { get; set; }
        public Nullable<int> SL_NAM_CK { get; set; }
        public Nullable<int> SL_NU_CK { get; set; }
        public Nullable<int> SL_NAM_KT { get; set; }
        public Nullable<int> SL_NU_KT { get; set; }
        public Nullable<int> SL_NAM_HT { get; set; }
        public Nullable<int> SL_NU_HT { get; set; }
        public Nullable<int> SL_TONG { get; set; }
        public Nullable<int> SL_TONG_HT { get; set; }
        public Nullable<int> SL_NAM_TT { get; set; }
        public Nullable<int> SL_NU_TT { get; set; }
        public Nullable<int> SL_TONG_TT { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<int> NGUOI_CAP_NHAT { get; set; }
        public string CHOT_DL { get; set; }
        public string LOAI_DL { get; set; }
    }
}
