//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QS_QUAN_TRANGEntities : DbContext
    {
        public QS_QUAN_TRANGEntities()
            : base("name=QS_QUAN_TRANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DM_CAP_BAC> DM_CAP_BAC { get; set; }
        public virtual DbSet<DM_CAP_BAC_CHO_QUAN_SO> DM_CAP_BAC_CHO_QUAN_SO { get; set; }
        public virtual DbSet<DM_CAP_BAC_HAM> DM_CAP_BAC_HAM { get; set; }
        public virtual DbSet<DM_CAP_BAC_NHOM> DM_CAP_BAC_NHOM { get; set; }
        public virtual DbSet<DM_DINH_MUC> DM_DINH_MUC { get; set; }
        public virtual DbSet<DM_DINH_MUC_SP> DM_DINH_MUC_SP { get; set; }
        public virtual DbSet<DM_DINH_MUC_SP_VT> DM_DINH_MUC_SP_VT { get; set; }
        public virtual DbSet<DM_DON_VI_DUOC_TRO_GIA> DM_DON_VI_DUOC_TRO_GIA { get; set; }
        public virtual DbSet<DM_LOAI_DT> DM_LOAI_DT { get; set; }
        public virtual DbSet<DM_LOAI_PHAM> DM_LOAI_PHAM { get; set; }
        public virtual DbSet<DM_LOAI_TC> DM_LOAI_TC { get; set; }
        public virtual DbSet<DM_NHOM_SAN_PHAM_BG> DM_NHOM_SAN_PHAM_BG { get; set; }
        public virtual DbSet<DM_NHOM_SAN_PHAM_BG_D> DM_NHOM_SAN_PHAM_BG_D { get; set; }
        public virtual DbSet<DM_NHOM_SP> DM_NHOM_SP { get; set; }
        public virtual DbSet<DM_NHOM_TC> DM_NHOM_TC { get; set; }
        public virtual DbSet<DM_NHOM_TC_CAP_BAC> DM_NHOM_TC_CAP_BAC { get; set; }
        public virtual DbSet<DM_NHOM_TC_KHU_VUC> DM_NHOM_TC_KHU_VUC { get; set; }
        public virtual DbSet<QS_CBCS_CHUYEN_LL_TH> QS_CBCS_CHUYEN_LL_TH { get; set; }
        public virtual DbSet<QS_CBCS_HT> QS_CBCS_HT { get; set; }
        public virtual DbSet<QS_CBCS_SD> QS_CBCS_SD { get; set; }
        public virtual DbSet<SP_SAN_PHAM> SP_SAN_PHAM { get; set; }
        public virtual DbSet<SP_SAN_PHAM_BG> SP_SAN_PHAM_BG { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TC_CBCS> TC_CBCS { get; set; }
        public virtual DbSet<TC_DON_VI_NH> TC_DON_VI_NH { get; set; }
        public virtual DbSet<TC_PHAM_NHAN> TC_PHAM_NHAN { get; set; }
        public virtual DbSet<TP_CB_BIET_PHAI> TP_CB_BIET_PHAI { get; set; }
        public virtual DbSet<TP_CB_CHO_HUU> TP_CB_CHO_HUU { get; set; }
        public virtual DbSet<TP_CB_CONG_TAC> TP_CB_CONG_TAC { get; set; }
        public virtual DbSet<TP_CB_DI_HOC> TP_CB_DI_HOC { get; set; }
        public virtual DbSet<TP_CB_TUYEN_MOI> TP_CB_TUYEN_MOI { get; set; }
        public virtual DbSet<TP_CS_NGHIA_VU> TP_CS_NGHIA_VU { get; set; }
        public virtual DbSet<QS_CBCS> QS_CBCS { get; set; }
    }
}
