//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_SAN_PHAM_BG
    {
        public long ID { get; set; }
        public long SP_ID { get; set; }
        public int NAM { get; set; }
        public Nullable<double> BIEU_GIA { get; set; }
        public Nullable<double> PHAN_TRAM_TRO_GIA { get; set; }
        public string MO_TA { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<int> NGUOI_CAP_NHAT { get; set; }
    }
}
