//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_SAN_PHAM
    {
        public long ID { get; set; }
        public string MA_H55 { get; set; }
        public string TEN_SP { get; set; }
        public string MO_TA { get; set; }
        public string IS_MAY_DO { get; set; }
        public Nullable<long> NHOM_SP_ID { get; set; }
        public Nullable<int> GIOI_TINH { get; set; }
        public Nullable<int> DVT_ID { get; set; }
        public Nullable<int> LUC_LUONG_ID { get; set; }
        public Nullable<int> NHOM_CB_ID { get; set; }
        public Nullable<long> SP_CHA_ID { get; set; }
        public string IS_VAT_TU { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<int> NGUOI_CAP_NHAT { get; set; }
        public Nullable<int> LOAI_HAM { get; set; }
        public Nullable<int> CAP_BAC_ID { get; set; }
        public string IS_NHAN_TIEN { get; set; }
        public string IS_NHAN_TRANG_PHUC { get; set; }
        public string IS_VAT_TU_CHINH { get; set; }
        public Nullable<double> SO_THU_TU { get; set; }
        public Nullable<double> TRO_GIA { get; set; }
        public string IS_HUY_MA { get; set; }
        public Nullable<System.DateTime> NGAY_HUY { get; set; }
        public string MaSP { get; set; }
        public string NhomSP_ID { get; set; }
        public string SPCha_ID { get; set; }
    }
}
