//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_UNITS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ST_UNITS()
        {
            this.ST_USERS = new HashSet<ST_USERS>();
        }
    
        public int UNIT_ID { get; set; }
        public string UNIT_CODE { get; set; }
        public string UNIT_NAME { get; set; }
        public string UNIT_DESC { get; set; }
        public Nullable<int> UNIT_PARENT_ID { get; set; }
        public string OFFICE_TYPE { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UNIT_LEVEL { get; set; }
        public string OFFICE_TEL { get; set; }
        public string DIRECTOR { get; set; }
        public string CHIEF_ACCOUNTANT { get; set; }
        public string MNG_UNIT { get; set; }
        public string DOMAIN_CODE { get; set; }
        public string ENABLED_FLAG { get; set; }
        public string UNIT_CLASS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ST_USERS> ST_USERS { get; set; }
    }
}
