//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_PHAM_NHAN
    {
        public int ID { get; set; }
        public Nullable<int> NHOM_TIEU_CHUAN_ID { get; set; }
        public Nullable<long> SP_ID { get; set; }
        public Nullable<int> LOAI_PHAM_ID { get; set; }
        public Nullable<int> GIOI_TINH { get; set; }
        public int NAM { get; set; }
        public Nullable<double> SO_LUONG_TC { get; set; }
        public Nullable<int> NIEN_HAN { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<int> NGUOI_CAP_NHAT { get; set; }
    }
}
