//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWTWebApi.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITEMS_SYSTEMEntities1 : DbContext
    {
        public ITEMS_SYSTEMEntities1()
            : base("name=ITEMS_SYSTEMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP> APPs { get; set; }
        public virtual DbSet<APPS_CONF> APPS_CONF { get; set; }
        public virtual DbSet<ST_PAGE_FUNCTIONS> ST_PAGE_FUNCTIONS { get; set; }
        public virtual DbSet<ST_PAGES_MENU> ST_PAGES_MENU { get; set; }
        public virtual DbSet<ST_PARAMETERS> ST_PARAMETERS { get; set; }
        public virtual DbSet<ST_PARAMETERS_EFF_DATE> ST_PARAMETERS_EFF_DATE { get; set; }
        public virtual DbSet<ST_ROLE_PAGES> ST_ROLE_PAGES { get; set; }
        public virtual DbSet<ST_ROLES> ST_ROLES { get; set; }
        public virtual DbSet<ST_UNITS> ST_UNITS { get; set; }
        public virtual DbSet<ST_USER_ROLES> ST_USER_ROLES { get; set; }
        public virtual DbSet<ST_USERS> ST_USERS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TF_TASKFLOW_CONF> TF_TASKFLOW_CONF { get; set; }
        public virtual DbSet<USER_LOCK> USER_LOCK { get; set; }
    }
}
