//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWTWebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TF_TASKFLOW_CONF
    {
        public string APP_CODE { get; set; }
        public string ITEMS_CLASS { get; set; }
        public int STEP_NO { get; set; }
        public string INIT_STATE { get; set; }
        public Nullable<int> EXEC_UNIT { get; set; }
        public string CONTROLLER_NAME { get; set; }
        public string ACTIONS_TO_NEXT { get; set; }
        public string STATE_OF_NEXT { get; set; }
        public string ACTIONS_TO_BACK { get; set; }
        public string STATE_OF_BACK { get; set; }
        public string STATE_LIST_OF_STEP { get; set; }
    }
}
