//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CAP_BAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_CAP_BAC()
        {
            this.DM_CAP_BAC_HAM = new HashSet<DM_CAP_BAC_HAM>();
        }
    
        public int ID { get; set; }
        public string TEN_CB { get; set; }
        public string MO_TA_CB { get; set; }
        public string IS_MAY_DO { get; set; }
        public Nullable<int> NIEN_HAN { get; set; }
        public Nullable<int> NHOM_CB_ID { get; set; }
        public Nullable<int> NHOM_TC_ID { get; set; }
        public Nullable<int> SO_THU_TU { get; set; }
    
        public virtual DM_CAP_BAC_NHOM DM_CAP_BAC_NHOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_CAP_BAC_HAM> DM_CAP_BAC_HAM { get; set; }
    }
}
