//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DINH_MUC_SP
    {
        public long ID { get; set; }
        public Nullable<int> DINH_MUC_ID { get; set; }
        public Nullable<long> SP_ID { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAPNHAT { get; set; }
        public Nullable<int> NGUOI_CAPNHAT { get; set; }
    }
}
