//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DINH_MUC_SP_VT
    {
        public long ID { get; set; }
        public Nullable<int> DINH_MUC_ID { get; set; }
        public Nullable<long> DINH_MUC_SP_ID { get; set; }
        public Nullable<long> SP_ID { get; set; }
        public Nullable<int> NHOM_VATTU_ID { get; set; }
        public Nullable<int> DVT_ID { get; set; }
        public string TEN_DVT { get; set; }
        public Nullable<double> SO_LUONG { get; set; }
        public Nullable<double> TYLE_HH { get; set; }
    }
}
