//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DONVI
    {
        public int ID { get; set; }
        public string TEN_DON_VI { get; set; }
        public string MO_TA { get; set; }
        public string PHIEN_HIEU { get; set; }
        public Nullable<int> NHOM_DON_VI_ID { get; set; }
        public Nullable<int> DON_VI_CHA_ID { get; set; }
        public Nullable<int> KHU_VUC_ID { get; set; }
        public string IS_QUAN_LY_KHO { get; set; }
        public Nullable<int> KHO_DEFAULT1_ID { get; set; }
        public Nullable<int> KHO_DEFAULT2_ID { get; set; }
        public Nullable<int> CONG_TY_DEFAULT1_ID { get; set; }
        public Nullable<int> CONG_TY_DEFAULT2_ID { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_TEL { get; set; }
        public string CONTACT_ID { get; set; }
        public string CONTACT_ADDRESS { get; set; }
        public Nullable<int> SO_NAM_DAO_TAO { get; set; }
        public string IS_TRO_GIA { get; set; }
        public string IS_CAN_BO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<int> NGUOI_CAP_NHAT { get; set; }
        public Nullable<int> SO_THU_TU_VUNG { get; set; }
        public string IS_CHECK_QUAN_SO { get; set; }
        public Nullable<System.DateTime> NGAY_CHECK { get; set; }
        public string MaDonVi { get; set; }
        public string DonViCha_ID { get; set; }
        public string KhoDefault1_ID { get; set; }
        public string KhoDefault2_ID { get; set; }
    }
}
