//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LUC_LUONG
    {
        public int ID { get; set; }
        public string TEN_LL { get; set; }
        public string MO_TA { get; set; }
        public string IS_TAN_BINH { get; set; }
        public Nullable<int> LL_CHA_ID { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<int> NGUOI_CAP_NHAT { get; set; }
        public Nullable<int> SO_THU_TU { get; set; }
        public string KY_HIEU_VIET_TAT { get; set; }
    }
}
