//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHOM_SP
    {
        public long ID { get; set; }
        public string MA_H55 { get; set; }
        public string TEN_NHOM_SP { get; set; }
        public string MO_TA { get; set; }
        public Nullable<int> LOAI_SP { get; set; }
        public Nullable<int> LOAI_NHOM_SP { get; set; }
        public Nullable<long> NHOM_SP_CHA_ID { get; set; }
        public Nullable<int> NHOM_TIEU_CHUAN_ID { get; set; }
        public string IS_VAT_TU { get; set; }
        public string IS_PHAM_NHAN { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<int> NGUOI_CAP_NHAT { get; set; }
        public Nullable<int> DVT_ID { get; set; }
        public string MaNhomSP { get; set; }
        public string NhomSPCha_ID { get; set; }
    }
}
