//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHOM_TC_CAP_BAC
    {
        public int ID { get; set; }
        public Nullable<int> NHOM_TC_ID { get; set; }
        public Nullable<int> NHOM_CB_ID { get; set; }
        public Nullable<int> NHOM_CB_CHA_ID { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<int> NGUOI_CAP_NHAT { get; set; }
    }
}
