//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITEMS_LISTEntities : DbContext
    {
        public ITEMS_LISTEntities()
            : base("name=ITEMS_LISTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DM_CONG_TY> DM_CONG_TY { get; set; }
        public virtual DbSet<DM_DON_VI_NHOM> DM_DON_VI_NHOM { get; set; }
        public virtual DbSet<DM_DON_VI_TINH> DM_DON_VI_TINH { get; set; }
        public virtual DbSet<DM_DONVI> DM_DONVI { get; set; }
        public virtual DbSet<DM_KHO> DM_KHO { get; set; }
        public virtual DbSet<DM_KHU_VUC> DM_KHU_VUC { get; set; }
        public virtual DbSet<DM_LOAI_HAM> DM_LOAI_HAM { get; set; }
        public virtual DbSet<DM_LUC_LUONG> DM_LUC_LUONG { get; set; }
        public virtual DbSet<LT_DATA_TYPES> LT_DATA_TYPES { get; set; }
        public virtual DbSet<LT_DESC_FLEX_COLUMN_USAGES> LT_DESC_FLEX_COLUMN_USAGES { get; set; }
        public virtual DbSet<LT_FLEX_VALUE_CATEGORIES> LT_FLEX_VALUE_CATEGORIES { get; set; }
        public virtual DbSet<LT_FLEX_VALUE_SETS> LT_FLEX_VALUE_SETS { get; set; }
        public virtual DbSet<LT_FLEX_VALUES> LT_FLEX_VALUES { get; set; }
    }
}
