//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_NHAP_KHO_CT
    {
        public long ID_NK_CT { get; set; }
        public long ID_TXN { get; set; }
        public Nullable<short> STT { get; set; }
        public Nullable<int> ID_HANG { get; set; }
        public string MA_HANG { get; set; }
        public string TEN_HANG { get; set; }
        public string DVT { get; set; }
        public Nullable<decimal> SO_LUONG_KH { get; set; }
        public Nullable<decimal> SO_LUONG_TT { get; set; }
        public Nullable<decimal> DON_GIA { get; set; }
        public Nullable<decimal> THANH_TIEN_KH { get; set; }
        public Nullable<decimal> THANH_TIEN_TT { get; set; }
        public string GHI_CHU { get; set; }
    }
}
