//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_NHAP_KHO
    {
        public long ID_TXN { get; set; }
        public int ID_KHO { get; set; }
        public string TEN_KHO { get; set; }
        public int ID_DON_VI { get; set; }
        public string TEN_DON_VI { get; set; }
        public Nullable<int> LOAI_NK { get; set; }
        public string SO_PHIEU { get; set; }
        public string NGAY_CT { get; set; }
        public Nullable<int> ID_HOP_DONG { get; set; }
        public string SO_HOP_DONG { get; set; }
        public string NGAY_KY_HD { get; set; }
        public string NGAY_HH_HD { get; set; }
        public Nullable<int> ID_NHA_CC { get; set; }
        public string TEN_NHA_CC { get; set; }
        public string LY_DO_NHAP { get; set; }
        public Nullable<int> ID_KE_HOACH { get; set; }
        public string SO_KE_HOACH { get; set; }
        public Nullable<decimal> TONG_TIEN { get; set; }
        public string TONG_TIEN_CHU { get; set; }
        public string NGAY_NK { get; set; }
        public string TRANG_THAI { get; set; }
        public string NGUON_KINH_PHI { get; set; }
        public string NGUON_HANG { get; set; }
        public Nullable<int> ID_NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<int> ID_NGUOI_CAP_NHAT { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<int> ID_NGUOI_GIAO { get; set; }
        public string TEN_NGUOI_GIAO { get; set; }
        public Nullable<int> ID_NGUOI_NHAN { get; set; }
        public string TEN_NGUOI_NHAN { get; set; }
        public string NHAP_TRA_DOI_CO { get; set; }
        public Nullable<int> ID_NGUOI_KY_1 { get; set; }
        public string TEN_NGUOI_KY_1 { get; set; }
        public string CV_NGUOI_KY_1 { get; set; }
        public string CB_NGUOI_KY_1 { get; set; }
        public Nullable<int> ID_NGUOI_KY_2 { get; set; }
        public string TEN_NGUOI_KY_2 { get; set; }
        public string CV_NGUOI_KY_2 { get; set; }
        public string CB_NGUOI_KY_2 { get; set; }
        public Nullable<int> ID_NGUOI_KY_3 { get; set; }
        public string TEN_NGUOI_KY_3 { get; set; }
        public string CV_NGUOI_KY_3 { get; set; }
        public string CB_NGUOI_KY_3 { get; set; }
        public Nullable<int> ID_NGUOI_KY_4 { get; set; }
        public string TEN_NGUOI_KY_4 { get; set; }
        public string CV_NGUOI_KY_4 { get; set; }
        public string CB_NGUOI_KY_4 { get; set; }
        public Nullable<int> ID_NGUOI_KY_5 { get; set; }
        public string TEN_NGUOI_KY_5 { get; set; }
        public string CV_NGUOI_KY_5 { get; set; }
        public string CB_NGUOI_KY_5 { get; set; }
    }
}
