//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KHO_HHEntities : DbContext
    {
        public KHO_HHEntities()
            : base("name=KHO_HHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KH_NHAP_KHO> KH_NHAP_KHO { get; set; }
        public virtual DbSet<KH_NHAP_KHO_CT> KH_NHAP_KHO_CT { get; set; }
    }
}
