//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LT_DATA_TYPES
    {
        public short DATA_TYPE_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string DATABASE_DATA_TYPE { get; set; }
        public string DATA_TYPE_FORMAT { get; set; }
        public string ENABLED_FLAG { get; set; }
    }
}
