//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LT_DESC_FLEX_COLUMN_USAGES
    {
        public int FLEX_VALUE_SET_ID { get; set; }
        public string FLEX_COLUMN_NAME { get; set; }
        public string FLEX_VALUE_SET { get; set; }
        public string FLEX_COL_DATA_TYPE { get; set; }
        public string ENABLED_FLAG { get; set; }
        public string REQUIRED_FLAG { get; set; }
        public string END_USER_COLUMN_NAME { get; set; }
        public string DISPLAY_FLAG { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public Nullable<int> COLUMN_SEQ_NUM { get; set; }
        public string DESCRIPTION { get; set; }
        public string CONTROL_NAME { get; set; }
        public string IS_CATEGORY_COLUMN { get; set; }
        public string FLEX_VALUE_CATEGORY { get; set; }
        public Nullable<int> FLEX_COL_DATA_LENGTH { get; set; }
        public string CONTROL_TYPE { get; set; }
        public string VIEW_COLUMN_NAME { get; set; }
        public string SHOW_ON_SEARCHING { get; set; }
        public string SHOW_ON_LIST { get; set; }
    }
}
