//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QS_CBCS_CHUYEN_LL_TH
    {
        public int ID { get; set; }
        public int NAM { get; set; }
        public int KY { get; set; }
        public string SO_HIEU { get; set; }
        public Nullable<int> GIOI_TINH { get; set; }
        public int DON_VI_CU_ID { get; set; }
        public int DON_VI_MOI_ID { get; set; }
        public Nullable<int> CAP_BAC_ID_CU { get; set; }
        public Nullable<int> CAP_BAC_ID_MOI { get; set; }
        public Nullable<int> LOAI_HAM_CU_ID { get; set; }
        public Nullable<int> LOAI_HAM_MOI_ID { get; set; }
        public string CHUC_VU_CU { get; set; }
        public string CHUC_VU_MOI { get; set; }
        public Nullable<int> LUC_LUONG_ID_CU { get; set; }
        public Nullable<int> LUC_LUONG_ID_MOI { get; set; }
        public Nullable<int> CHO_HUU { get; set; }
        public Nullable<int> DI_HOC { get; set; }
        public Nullable<int> BIET_PHAI { get; set; }
        public Nullable<int> CAT_QUAN_SO { get; set; }
        public Nullable<int> CO_GIAY { get; set; }
        public Nullable<int> CO_MU { get; set; }
        public Nullable<int> CO_QA { get; set; }
        public Nullable<int> DK_HIEN_VAT { get; set; }
        public Nullable<int> DK_DOI_TC { get; set; }
        public Nullable<int> NAM_NIEN_HAN { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<int> NGUOI_CAP_NHAT { get; set; }
    }
}
