//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_ROLE_PAGES
    {
        public int ROLE_ID { get; set; }
        public int PAGE_ID { get; set; }
        public string APP_CODE { get; set; }
        public string CONTROL_STRING { get; set; }
        public string ENABLED_FLAG { get; set; }
    }
}
