//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_CBCS
    {
        public long ID { get; set; }
        public Nullable<int> NHOM_TIEU_CHUAN_ID { get; set; }
        public long SP_ID { get; set; }
        public Nullable<int> GIOI_TINH { get; set; }
        public int NAM { get; set; }
        public Nullable<int> MUA { get; set; }
        public Nullable<int> NHOM_CB_ID { get; set; }
        public string IS_MO_RONG { get; set; }
        public string IS_THEM { get; set; }
        public Nullable<double> SO_LUONG_TC { get; set; }
        public Nullable<int> LOAI_TC { get; set; }
        public Nullable<int> NIEN_HAN { get; set; }
        public Nullable<int> LUC_LUONG_ID { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public Nullable<int> NGUOI_CAP_NHAT { get; set; }
    
        public virtual DM_NHOM_TC DM_NHOM_TC { get; set; }
    }
}
