//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP_CB_DI_HOC
    {
        public long ID { get; set; }
        public string SO_HIEU { get; set; }
        public string GIOI_TINH { get; set; }
        public Nullable<int> CAP_BAC_ID { get; set; }
        public Nullable<int> LOAI_HAM_ID { get; set; }
        public string CHUC_VU { get; set; }
        public Nullable<int> DON_VI_ID { get; set; }
        public Nullable<int> LUC_LUONG_ID { get; set; }
        public Nullable<int> CO_GIAY { get; set; }
        public Nullable<int> CO_MU { get; set; }
        public Nullable<int> CO_QA { get; set; }
        public Nullable<int> LOAI { get; set; }
        public Nullable<int> LOAI_TUYEN { get; set; }
        public string HIEU_LUC { get; set; }
        public Nullable<long> TXN_ID { get; set; }
        public string DANG_KY_HV { get; set; }
        public string CAC_TRUONG_ERR { get; set; }
        public string MO_TA_ERR { get; set; }
    }
}
