//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONVERSATION
    {
        public System.Guid CONVERSATION_ID { get; set; }
        public string SEND_USER { get; set; }
        public string RECIVE_USER { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<bool> ISREAD { get; set; }
        public Nullable<int> ATTACH_FILE_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
