//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE
    {
        public int FILE_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_URL { get; set; }
        public string FILE_EXTEND { get; set; }
    }
}
