//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWTWebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_PAGES_MENU
    {
        public int PAGE_ID { get; set; }
        public string APP_CODE { get; set; }
        public string PAGE_NAME { get; set; }
        public string PAGE_DESC { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public Nullable<int> ORDER_LEVEL { get; set; }
        public string MODULE_CODE { get; set; }
        public string CSS_CLASS { get; set; }
        public string HREF_URL { get; set; }
        public string PERMISSION_REQUIRE { get; set; }
        public string ENABLED_FLAG { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<int> LAST_UPDATED_BY { get; set; }
    }
}
