//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_PARAMETERS
    {
        public string PARAM_ID { get; set; }
        public string APP_CODE { get; set; }
        public string PARAM_CODE { get; set; }
        public string PARAM_NAME { get; set; }
        public string PARAM_VALUE { get; set; }
        public string PARAM_DESC { get; set; }
        public string PARAM_VALUE_TYPE { get; set; }
        public string APP_CAN_EDIT { get; set; }
        public string MODULE { get; set; }
        public string SCOPE { get; set; }
        public string DOMAIN_CODE { get; set; }
        public Nullable<int> UNIT_ID { get; set; }
        public Nullable<int> ID_BO_PHAN { get; set; }
        public string ENABLED_FLAG { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string USING_EFFECT_DATE { get; set; }
        public string DISPLAY_FLAG { get; set; }
    }
}
